global:
    debug: False
    refresh_interval: 1

blocks:
    - type: uptime
      update_interval: 0.5
      label: "U: "
      duration_format: "%d days, %0h:%0m:%0s"

    - type: raid
      label: "R: "
      color: "#71b58e"

    - type: disk
      label: "D: "
      filesystems:
          /: 90
          /home: 90

    - type: load
      label: "L: "
      color: "#71b58e"
      crit_load: 4

    - type: memory
      label: "M: "
      crit_mem: 1

    - type: temperature
      color: "#71b58e"
      cpu_temp_path: /sys/devices/platform/coretemp.0/hwmon
      crit_temp: 50

    - type: interface
      label: "E: "
      interface_name: enp3s0

    - type: volume
      label: "V: "
      color: "#71b58e"
      update_interval: 60
      update_signal: 8
      mixer_device: default
      channel: Master

    - type: time
      update_interval: 0.5
      time_format: 2006-01-02 15:04:05
